### ISSUE TITLE
一群中国人开发项目，居然没有母语的中文文档？想问开发者是什么心理？？？

### ISSUE THREAD

**Issue by huluBrother** [alibaba/fescar#610]
....

**Comment by huluBrother** [comment]
想用中文表达一下

**Comment by xingfudeshi** [comment]
译文
Thank you for your attention to Fescar. As an open source project, we hope that every country around the world can participate, and English is the world common language, so, we hope you can describe your issue in English as much as possible, so that you can make more and more people focus on the issue of accelerating the solution of the problem at the same time can also met the same problem for other people find a common place of the communication. Of course, you can also directly describe your issue in Chinese and let the robot translate it into English automatically. About the documentation, we will support English and Chinese, you can refer to here[url]https://github.com/alibaba/fescar/wiki/Home_Chinese[url], but Fescar is in the early stage of open source, the documentation is not perfect, if you are interested in helping us improve the relevant documentation, we are very welcome.
in

**Comment by xingfudeshi** [comment]
Fescar's DingTalk group number is 23171167. You can join it and communicate in Chinese.

**Comment by slievrly** [comment]
please read our wiki https://github.com/alibaba/fescar/wiki/Home_Chinese

**Comment by jovany-wang** [comment]
Thanks, I think this is a good point! We are going to support readme and docs in Chinese.
And as @slievrly mentioned, you can read the wiki in Chinese.

**Comment by wenfer** [comment]
可能是中文不好吧

**Comment by JacksonTian** [comment]
好多美国人开发的项目也没有美文文档，真是搞不懂他们是怎么想的。

**Comment by cmonkey** [comment]
可能是为了能上apache 吧

**Comment by bianlizuozishu** [comment]
What do you think? This is open source software and if you feel the documentation is not working you can supplement it, not condemn it.

**Comment by SoyMeng** [comment]
英文从表义上比中文更准确

**Comment by iPhotoner** [comment]
楼猪太过激动，什么心态，哈哈
