### ISSUE TITLE
 fescar-server 0.4. and nacos server 1.0.0RC1 ERROR~!

### ISSUE THREAD

**Issue by vikenlove** [alibaba/fescar#647]
this is  a  error log about naming.log . when is use fescar-server 0.4. and nacos server 1.0.0RC1.
i can't start fescar-server .i ask to nacos team, he tell me  ip":"viken-acer" is not right IP address.

and viken-acer is my HostName . so  please help me  how config it :(

`01 2019-03-22 14:42:36.486 INFO [main :c.a.n.c.naming] [BEAT] [] [] adding beat: {"cluster":"default","ip":"viken-acer","metadata":{},"port":8091,"scheduled":false,"serviceName":"serverAddr","weight":1.0} to beat map.
01 2019-03-22 14:42:36.578 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] [] [] public registering service serverAddr with instance: {"clusterName":"default","enabled":true,"ip":"viken-acer","metadata":{},"port":8091,"valid":true,"weight":1.0}
01 2019-03-22 14:42:36.594 ERROR [main :c.a.n.c.naming] [] [] [CALL-SERVER] failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid:Fei-Wang:8091:unknown:default_1.0_true_false_default
01 2019-03-22 14:42:36.596 ERROR [main :c.a.n.c.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(localhost
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
	at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:152)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
	at com.alibaba.fescar.server.Server.main(Server.java:88)
`

**Comment by xingfudeshi** [comment]
Dose Fescar work with nacos 0.8?

**Comment by vikenlove** [comment]
@xingfudeshi  i was solved it 。 when we use nacos and fescar ,we must config LAN IP mapping hostname.
windwos host : C:\Windows\System32\drivers\etc

**Comment by xingfudeshi** [comment]
@vikenlove ok fine

**Comment by vikenlove** [comment]
@xingfudeshi the source code NacosRegistryServiceImpl 
`  @Override
    public void register(InetSocketAddress address) throws Exception {
        validAddress(address);
    // address.getHostName() ? why is it addr.getHostAddress().
        getNamingInstance().registerInstance(PRO_SERVER_ADDR_KEY, address.getHostName(), address.getPort(),
            getClusterName());
    }`

i don't know why does write it like this ? in the windows ,start up fescar.bat we will get address.getHostName() value  is computer name ,but slievrly run code by IDE ,get value is IP address.

**Comment by xingfudeshi** [comment]
@vikenlove address.getHostName() may return different value.Please note that  this depends on how you created the InetAddress object.
1.
InetAddress address = InetAddress.getLocalHost();
System.out.println(address.getHostName());  // your computer's name
2.
InetAddress address = InetAddress.getByName("fescar.io");
System.out.println(address.getHostName());  // will return fescar.io directly without query DNS
3.
InetAddress address = InetAddress.getByName("123.123.18.66");
System.out.println(address.getHostName());  // will query DNS，if DNS found the corresponding Host name，then you will get it.otherwise,getHostName will return ip.

**Comment by vikenlove** [comment]
@vikenlove  this is my code `InetAddress address = InetAddress.getLocalHost();
System.out.println(address.getHostName()); // your computer's name`
So I get a value, this is my computer name. The source code for fescar is address.getHostName(). I think this should be addr.getHostAddress(). Because when starting the fescar server, we don't need conifg ip and fescar should automatically get our server IP.

**Comment by xingfudeshi** [comment]
Please check the line 152 of source code of com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer:
`
RegistryFactory.getInstance().register(new InetSocketAddress(XID.getIpAddress(), XID.getPort()));
`
This is the third way I described above to create InetAddress.


`3.InetAddress address = InetAddress.getByName("123.123.18.66");
System.out.println(address.getHostName()); `
will query from DNS，if DNS found the corresponding Host name，then you will get it.otherwise,getHostName will return ip.

**Comment by slievrly** [comment]
mark, i will resolve

**Comment by myishuohuo** [comment]
Thank you. Problem solved
